src/main/java/com/nullteam6/controller/AnimeController.java
src/main/java/com/nullteam6/controller/CategoryController.java
src/main/java/com/nullteam6/controller/UserController.java
src/main/java/com/nullteam6/models/Anime.java
src/main/java/com/nullteam6/models/AnimeTemplate.java
src/main/java/com/nullteam6/service/AnimeService.java
src/main/java/com/nullteam6/service/CategoryService.java
src/main/java/com/nullteam6/utility/PaginatedList.java

CategoryController will also return a list of categories per anime by id.

API supports searching for anime by text and id. 

---

src/main/java/com/nullteam6/controller/LoginController.java
src/main/java/com/nullteam6/models/LoginTemplate.java
src/main/java/com/nullteam6/models/User.java
src/main/java/com/nullteam6/models/UserTemplate.java
src/main/java/com/nullteam6/service/UserDAO.java
src/main/java/com/nullteam6/service/UserDAOImpl.java
src/main/java/com/nullteam6/utility/PBKDF2Hasher.java

Initial login implementation

---

pom.xml
src/main/java/com/nullteam6/controller/AnimeController.java
src/main/java/com/nullteam6/service/AnimeService.java
src/main/java/com/nullteam6/utility/KitsuUtility.java
src/main/java/com/nullteam6/utility/PaginatedList.java

Search API Functionality now supports pagination.

---

src/main/java/com/nullteam6/controller/AnimeBacklogController.java
src/main/java/com/nullteam6/controller/AnimeController.java
src/main/java/com/nullteam6/controller/UserController.java
src/main/java/com/nullteam6/models/Anime.java
src/main/java/com/nullteam6/models/AnimeBacklog.java
src/main/java/com/nullteam6/service/AnimeBacklogDAO.java
src/main/java/com/nullteam6/service/AnimeBacklogDAOImpl.java
src/main/java/com/nullteam6/service/AnimeDAO.java
src/main/java/com/nullteam6/service/AnimeDAOImpl.java
src/main/java/com/nullteam6/service/AnimeService.java
src/main/java/com/nullteam6/service/UserDAO.java
src/main/java/com/nullteam6/service/UserDAOImpl.java

Dirty Commit. Start of Backlog functionality. Along with other changes

---

src/main/java/com/nullteam6/service/UserDAO.java
src/main/java/com/nullteam6/service/UserDAOImpl.java
src/main/webapp/WEB-INF/BackEnd-servlet.xml.default
src/main/webapp/WEB-INF/web.xml

Fix bug breaking bug of dirty commit in UserDAOImpl.java

---

pom.xml
src/main/java/com/nullteam6/models/Profile.java
src/main/java/com/nullteam6/service/ProfileDAOImpl.java
src/main/java/com/nullteam6/service/UserDAOImpl.java

git borked but have some bug fixes

profile bug fixes

---

src/main/java/com/nullteam6/controller/LoginController.java
src/main/java/com/nullteam6/controller/UserController.java
src/main/webapp/WEB-INF/web.xml

More CORS stuff. Reimplemented the LoginController to no break FrontEnd.

---

pom.xml
src/main/java/com/nullteam6/SpringSecurityInitializer.java
src/main/java/com/nullteam6/config/SecurityConfig.java
src/main/java/com/nullteam6/controller/AnimeBacklogController.java
src/main/java/com/nullteam6/controller/AnimeController.java
src/main/java/com/nullteam6/controller/CategoryController.java
src/main/resources/log4j2.xml
src/main/webapp/WEB-INF/keycloak.json
src/main/webapp/WEB-INF/web.xml

Secured /user endpoint using OAuth2.

Spring Security

---

src/main/java/com/nullteam6/config/SecurityConfig.java
src/main/java/com/nullteam6/controller/AnimeBacklogController.java
src/main/java/com/nullteam6/controller/AnimeController.java
src/main/java/com/nullteam6/service/AnimeService.java

Implemented trending anime at /anime/trending and also secured the anime backlog endpoint.

Trending Anime

---

src/main/java/com/nullteam6/service/AnimeService.java

Fixed typo in URL causing a NullPointerException

---

.gitignore
pom.xml
src/main/java/com/nullteam6/controller/AnimeBacklogController.java
src/main/java/com/nullteam6/controller/AnimeController.java
src/main/java/com/nullteam6/controller/CategoryController.java
src/main/java/com/nullteam6/controller/LoginController.java
src/main/java/com/nullteam6/controller/UserController.java
src/main/java/com/nullteam6/models/AnimeBacklog.java
src/main/java/com/nullteam6/models/Profile.java
src/main/java/com/nullteam6/service/AnimeBacklogDAOImpl.java
src/main/java/com/nullteam6/service/AnimeDAOImpl.java
src/main/java/com/nullteam6/service/AnimeService.java
src/main/java/com/nullteam6/service/CategoryService.java
src/main/java/com/nullteam6/service/ProfileDAOImpl.java
src/main/java/com/nullteam6/service/UserDAOImpl.java
src/main/java/com/nullteam6/utility/KitsuUtility.java
src/test/java/com/nullteam6/controller/AnimeControllerTest.java
src/test/java/com/nullteam6/controller/CategoryControllerTest.java
src/test/resources/BackEnd-servlet-test.default.xml

Documented the backend using JavaDoc

Refactoring

---

src/main/java/com/nullteam6/controller/UserController.java
src/main/java/com/nullteam6/service/UserDAOImpl.java

Added an endpoint and associated code to view all LDAP users. Intended for admins.

Admin: Added some Admin stuff

---

src/main/java/com/nullteam6/controller/ProfileController.java
src/main/java/com/nullteam6/models/Profile.java
src/main/java/com/nullteam6/service/ProfileDAO.java
src/main/java/com/nullteam6/service/ProfileDAOImpl.java
src/main/java/com/nullteam6/service/UserDAO.java
src/main/java/com/nullteam6/service/UserDAOImpl.java

Modified the Profile model to add a following list. Additionally added search functionality to the Profile controller and DAO.

Feature: Friends & Search

---

src/main/java/com/nullteam6/models/Profile.java
src/main/java/com/nullteam6/service/UserDAOImpl.java

Refactored UserDAOImpl profile creation. It will now instantiate a list for the followingList. Added getter/setter for followingList in Profile.

Refactor: UserDAO

---

src/main/java/com/nullteam6/controller/ProfileController.java
src/main/java/com/nullteam6/controller/UserController.java

enabled transactions on the user and profile controller

Bugfix: Transactions

---

src/main/java/com/nullteam6/controller/ProfileController.java
src/main/java/com/nullteam6/controller/UserController.java
src/main/java/com/nullteam6/models/Profile.java
src/main/java/com/nullteam6/service/ProfileDAOImpl.java

This should correct the 500 that Front End is getting occasionally on updating profile. As I have been unable to reproduce the same exception locally with postman... this is a *theoretical* fix.

Bugfix: NonUniqueObjectException

---

src/main/java/com/nullteam6/service/ProfileDAOImpl.java

Bugfix: Profile Updates pt2

---

src/main/java/com/nullteam6/controller/LoginController.java
src/main/java/com/nullteam6/controller/ProfileController.java
src/main/java/com/nullteam6/controller/UserController.java
src/main/java/com/nullteam6/models/Profile.java
src/main/java/com/nullteam6/models/ProfileDTO.java
src/main/java/com/nullteam6/models/UserDTO.java
src/main/java/com/nullteam6/service/ProfileDAO.java
src/main/java/com/nullteam6/service/ProfileDAOImpl.java
src/main/java/com/nullteam6/service/UserDAO.java
src/main/java/com/nullteam6/service/UserDAOImpl.java

Bugfix: Profile Updates pt3

---

src/main/java/com/nullteam6/models/ProfileDTO.java

Added a default constructor to the ProfileDTO.

Bugfix: ProfileDTO

---

src/main/java/com/nullteam6/models/AnimeBacklog.java
src/main/java/com/nullteam6/service/AnimeService.java

The testing king demands moar tests!!!!

Testing: Moar Testing!

---

src/main/java/com/nullteam6/controller/LoginController.java
src/main/java/com/nullteam6/controller/UserController.java
src/main/java/com/nullteam6/models/Profile.java
src/main/java/com/nullteam6/service/ProfileDAOImpl.java
src/main/java/com/nullteam6/service/UserDAO.java
src/main/java/com/nullteam6/service/UserDAOImpl.java
src/test/java/com/nullteam6/controller/AnimeControllerTest.java
src/test/java/com/nullteam6/controller/LoginControllerTest.java
src/test/java/com/nullteam6/controller/ProfileControllerTest.java
src/test/java/com/nullteam6/controller/UserControllerTest.java

Added more tests. Also cleaned up some deprecated and unused code.

Testing: More tests
